name: CPanel Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install deps
        run: npm ci
      - name: Build deps
        run: npm run build
      - name: Production artifact
        uses: actions/upload-artifact@main
        with:
          name: build
          path: build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Download artifact
        uses: actions/download-artifact@main
        with:
          name: dist
          path: dist
      - name: Sync
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ftp.karmosimesek.hu
          username: deploy@karmosimesek.hu
          password: ${{ secrets.FTP_PASSWORD }}
